// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxvVhI4QQppoKL6cCiaZu2o46l7fdPduI',
    appId: '1:807915091232:web:7a30ba1654c3feb0541345',
    messagingSenderId: '807915091232',
    projectId: 'pluggo-65ffb',
    authDomain: 'pluggo-65ffb.firebaseapp.com',
    storageBucket: 'pluggo-65ffb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFjruURM877Ef5V5-AhIHY3rCR9FoUcxk',
    appId: '1:807915091232:android:45323736d1bc0ca8541345',
    messagingSenderId: '807915091232',
    projectId: 'pluggo-65ffb',
    storageBucket: 'pluggo-65ffb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNmvMLP00PZuHiWdmx53MDxusCGy458nM',
    appId: '1:807915091232:ios:bb20f2c6ffb7e4b8541345',
    messagingSenderId: '807915091232',
    projectId: 'pluggo-65ffb',
    storageBucket: 'pluggo-65ffb.firebasestorage.app',
    iosClientId: '807915091232-9b6gsbcbecdmb87lvqcljj1o9drd3nfr.apps.googleusercontent.com',
    iosBundleId: 'com.pluggo.pluggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNmvMLP00PZuHiWdmx53MDxusCGy458nM',
    appId: '1:807915091232:ios:bb20f2c6ffb7e4b8541345',
    messagingSenderId: '807915091232',
    projectId: 'pluggo-65ffb',
    storageBucket: 'pluggo-65ffb.firebasestorage.app',
    iosClientId: '807915091232-9b6gsbcbecdmb87lvqcljj1o9drd3nfr.apps.googleusercontent.com',
    iosBundleId: 'com.pluggo.pluggo',
  );
}
