service: api-plugGo

provider:
  name: aws
  region: us-east-1
  runtime: provided.al2

plugins:
  - ./vendor/bref/bref
  - serverless-ignore
  - ./vendor/bref/extra-php-extensions        

functions:
  api-backend:
    handler: src/index.php
    vpc:
      securityGroupIds:
        - sg-0f9e946870959fc9c
      subnetIds:
        - subnet-095e969481a1e353f
        - subnet-010fa3a9ac227893e
    description: ""
    timeout: 28
    memorySize: 128
    layers:
      - ${bref:layer.php-81-fpm}
      - ${bref-extra:gd-php-81}
    events:
      - httpApi: "*"
package:
  patterns:
    - "!node_modules/**"
    - "!test/**"
